apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pastebin
  name: pastebin
  namespace: pastebin
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pastebin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pastebin
    spec:
      containers:
      - image: ghcr.io/samihda/pastebin:037b79cea5f2d1a122486a59fee4a2d2290c9158
        imagePullPolicy: IfNotPresent
        name: pastebin
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 30
        ports:
        - containerPort: 8000
          name: pastebin-http
          protocol: TCP
        env:
        - name: PASTEBIN_ROOT
          value: "/var/www"
        volumeMounts:
        - mountPath: /var/www
          name: pastebin-storage
      volumes:
      - name: pastebin-storage
        persistentVolumeClaim:
          claimName: pastebin-pvc
