apiVersion: v1
kind: Service
metadata:
  namespace: pastebin
  name: pastebin
  labels:
    app: pastebin
spec:
  ports:
  - name: pastebin-http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: pastebin
  loadBalancerIP: 192.168.178.12
  type: LoadBalancer
